services:
  Bot:
    image: bot
    build:
      context: ./Bot
      network: host
    restart: always
  Parser:
    image: parser
    build:
      context: ./Parse
      network: host
    restart: always