services:
  Bot:
    image: bot
    build:
      context: ./Bot
    networks:
      - app-network
    restart: always
  Parser:
    image: parser
    build:
      context: ./Parse
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge